# Tokyo Night — 配色主题
# 来源参考: https://github.com/dexpota/kitty-themes
# 可通过 `kitty +kitten themes` 切换为其它主题后覆盖本文件

foreground              #c0caf5
background              #1a1b26
selection_foreground    #1a1b26
selection_background    #33467c
cursor                  #c0caf5
cursor_text_color       #1a1b26

# 黑
color0   #15161e
color8   #414868
# 红
color1   #f7768e
color9   #f7768e
# 绿
color2   #9ece6a
color10  #9ece6a
# 黄
color3   #e0af68
color11  #e0af68
# 蓝
color4   #7aa2f7
color12  #7aa2f7
# 品红
color5   #bb9af7
color13  #bb9af7
# 青
color6   #7dcfff
color14  #7dcfff
# 白
color7   #a9b1d6
color15  #c0caf5
